### ISSUE TITLE
Python3.6 代码运行错误

### ISSUE THREAD

**Issue by zaf05** [bobye/batchnorm_prune#3]
训练过程中，当训练完毕
 

1. mon_sess.should_stop()=True时报错

     # training and sparisifying 
      while not mon_sess.should_stop():
        mon_sess.run(train_op)  
2.错误定位在cifar10_train.py中112号处会发生错cifprune_op = dt.prune(tf.get_collection('is prune'))
3.错误描述
2019-10-11 17:37:10.286919: W tensorflow/core/framework/op_kernel.cc:1490] Unknown: KeyError: b'g2b2c0/BatchNorm/gamma'
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/home/ubuntu/Downloads/batchnorm_prune-master/src/python/cifar10/batchnorm_prune/Transformer.py", line 111, in <lambda>
    collection.append(tf.py_func(lambda a, b: self.flow.get_channel_pruned(a, b),

  File "/home/ubuntu/Downloads/batchnorm_prune-master/src/python/cifar10/batchnorm_prune/Graph.py", line 155, in get_channel_pruned
    print(self.edgename_map[varname])

KeyError: b'g2b2c0/BatchNorm/gamma'

本人环境：
python3.6
tensorflow1.14
请作者看看，谢谢

**Comment by bobye** [comment]
can you try python2.7? 

I developed this code using python2.7 + tensorflow1.14. I was able to follow the README with no crashes.  

Its behavior under python3.6 is unknown to me. I know the python2 will soon be deprecated. I will try to fix the issue for python3.5 or higher.

**Comment by zaf05** [comment]
python2.7的环境我还没尝试，python3.6是可以训练，就是到最后一次，训练完成开始剪枝的时候报错在collection.append(tf.py_func(lambda a, b: self.flow.get_channel_pruned(a, b),[tf.constant(varname), v], tf.bool))  这儿，我很困惑。

**Comment by bobye** [comment]
It may be the pickle library is incompatible between python 2 and 3. Will let you know if I figured out.

**Comment by zaf05** [comment]
谢谢你耐心指导，pickle我已经在导包时候，换成python3.x的写法，你可以试试，在python3.x环境中，是不是与我同样的问题，方便话传一份python3.x环境代码，再次感谢。

**Comment by zaf05** [comment]
Hi,我又调试了一遍在Graph.py文件中get_channel_pruned添加了 varname = str(varname, encoding="utf8")，因为在我python3.6环境中出现varname为二进制，
KeyError: b'g1b1c0/BatchNorm/gamma'这样的错误，经过转换后，现在代码可以完全运行，没有任何错误，不知道我改的对不对，谢谢。
代码如下：

   def get_channel_pruned(self, varname, v):
        varname = str(varname, encoding="utf8")
        if len(self.edgename_map[varname]) == 2:
            v_in, v_out = self.edgename_map[varname]
            for i in range(v.shape[0]):
                if v[i]:
                    v1 = v_in  + "_%d" % i
                    v2 = v_out + "_%d" % i
                    self.nodes[v1].o.remove(v2)
                    self.nodes[v2].i.remove(v1)

**Comment by bobye** [comment]
太好了 有空麻烦交一个Pull Request 我刚好可以验证一下是不是兼容python2

**Comment by bobye** [comment]
@zaf05 Hi, could you verify if you can run the latest commit?
